### ISSUE TITLE
panic in single-replica propagation stage

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#128]
<img width="1168" alt="Screenshot 2024-02-20 at 09 35 12" src="https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/d332e7ac-a895-4dd4-a17b-d1f73a11174d">

```
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] Running tests for Replication > Stage #11: Single-replica propagation
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ ./spawn_redis_server.sh --port 6379
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] Logs from your program will appear here!
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli PING
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] PONG received.
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli REPLCONF listening-port 6380
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] OK received.
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli PSYNC ? -1
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] FULLRESYNC 64df12bbf8304c23b900d67ec4171016abcd1234 0 received.
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] Successfully received RDB file from master.
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] Setting key foo to 123
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli SET foo 123
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] Setting key bar to 456
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli SET bar 456
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] Setting key baz to 789
Feb 20 05:47:46 d89d927b6e6378 vector [replication-11] $ redis-cli SET baz 789
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] Role of calling redis type: master
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] arraySize = 3, the string to print: 3
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] 
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] *3
Feb 20 05:47:46 d89d927b6e6378 vector [your_program] 
Feb 20 05:47:46 d89d927b6e6378 vector error panic: runtime error: index out of range [0] with length 0
Feb 20 05:47:46 d89d927b6e6378 vector goroutine 301 [running]:
Feb 20 05:47:46 d89d927b6e6378 vector github.com/codecrafters-io/redis-tester/internal.FakeRedisNode.readAndAssertMessagesWithSkip({0xc0000126b0, 0xc0000126b8, 0xc00038aa80, {0x0, 0x0}}, {0xc0000b3e58, 0x3, 0x3}, {0x6e012c, 0x6}, ...)
	/home/runner/work/redis-tester/redis-tester/internal/util.go:399 +0x315
Feb 20 05:47:46 d89d927b6e6378 vector github.com/codecrafters-io/redis-tester/internal.testReplMasterCmdProp(0xc00038c4e0)
	/home/runner/work/redis-tester/redis-tester/internal/test_repl_master_cmd_prop.go:55 +0x88f
Feb 20 05:47:46 d89d927b6e6378 vector github.com/codecrafters-io/tester-utils.testRunner.Run.func1()
	/home/runner/go/pkg/mod/github.com/codecrafters-io/tester-utils@v0.2.12/test_runner.go:63 +0x2e
Feb 20 05:47:46 d89d927b6e6378 vector created by github.com/codecrafters-io/tester-utils.testRunner.Run
	/home/runner/go/pkg/mod/github.com/codecrafters-io/tester-utils@v0.2.12/test_runner.go:62 +0x35b
Feb 20 05:47:46 d89d927b6e6378 vector Failed to run tester: exit status 2
Feb 20 05:47:46 d89d927b6e6378 vector error CodeCrafters internal error: exit status 2
```

**Comment by rohitpaulk** [comment]
Thanks to @suond for highlighting this!

**Comment by rohitpaulk** [comment]
This should be fixed in the new tester!
